### ISSUE TITLE
reformat solver interface table

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/juliaopt.org#12]
- The JuMP column doesn't transmit much information since all solvers are now supported.
- Incorporate Convex.jl into the table. All LP/SOCP solvers are supported so maybe again not too useful to make a new column?
- Merge MILP/MISOCP/MINLP into a single "integer variables" column?

**Comment by madeleineudell** [comment]
* It's not clear whether JuMP and Convex are columns or rows. Convex connects to *some* kinds of solvers to solve *some* kinds of problems, eg it connects to Mosek but cannot solve MINLPs with Mosek.
* Is it true that if a solver solves problems with integer variables, and it solves problems of type X, then it solves MIXs? This is *not* true for Convex or Mosek, which can solve SDPs and can solve MISOCPs but can't solve MISDPs (though I've not tried Mosek yet; please correct me if that's false).

**Comment by mlubin** [comment]
I like the idea of putting Convex and JuMP in as (differently styled) rows. We can use footnotes for the rare (and hopefully transitional) cases where a solver supports the problem class but not through MPB/JuMP/Convex.

It's probably not true that all solvers that support MIPs and SDPs also support MISDPs. We can either handle this with footnotes or some other restructuring.

**Comment by tkelman** [comment]
And is the Mosek NLP/MINLP solver only capable of solving convex problems or am I imagining seeing that elsewhere?

**Comment by mlubin** [comment]
Yeah, that deserves a footnote.
