### ISSUE TITLE
new paper "using juliaopt"

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/juliaopt.org#20]
http://arxiv.org/abs/1506.03039

@madeleineudell is credited in the acknowledgements

**Comment by IainNZ** [comment]
Hah neat. They spelled it out: `Julia for Mathematical Programming [20]`

**Comment by IainNZ** [comment]
There is also http://arxiv.org/pdf/1506.04088.pdf !

**Comment by IainNZ** [comment]
"As in Section 3.1, we implemented the variational solution using the autodifferentiation
software JuMP [19]. "
